### ISSUE TITLE
Do not put these scripts in any folder.

### ISSUE THREAD

**Issue by My12123** [Kiteretsu77/FAST_Anime_VSR#12]
https://github.com/Kiteretsu77/FAST_Anime_VSR/tree/main/Installation_script
@Kiteretsu77 
Why can user @HikariDawn777 make changes, but without Verified "This commit was created on GitHub.com and signed with GitHub’s verified signature." and without a pull request?

**Comment by HikariDawn777** [comment]
This is my second account. I push with a mix.

**Comment by Kiteretsu77** [comment]
This is my second account. I push with a mix.
