### ISSUE TITLE
Error Code 2: OutOfMemory (no further information)

### ISSUE THREAD

**Issue by My12123** [Kiteretsu77/FAST_Anime_VSR#9]
```python
process the image with height 720 and width 1280
Use float16 mode in TensorRT
Generating the TensorRT weight ........
[09/04/2023-22:30:21] [TRT] [E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::145] Error Code 2: OutOfMemory (no further information)
```

**Comment by Kiteretsu77** [comment]
I think that this is because your 720x1280 input is too big for your GPU to handle TensorRT weight transfer. Generally, 720x1280 = 921,600 pixels, which is 3 times more pixels than 480x640=307200. It is a huge gap between these two resolutions.

**Comment by Kiteretsu77** [comment]
I can try to develop a new feature that the whole code runs with only partition frames (1/3 frame), which will not consider any full-frame mode. This may make higher resolution images work on lower computation power GPU.

**Comment by My12123** [comment]
It is not necessary for me to load into the shared memory of the GPU in case of an error.
